#include "umap_layout.hpp"

#include <bit>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>

/*
 * Algorithmic reference:
 *   umap-learn 0.5.12, umap/layouts.py and umap/utils.py
 *     BSD-3-Clause, Copyright (c) 2017 Leland McInnes.
 *
 * Memory ownership and the bounded caller-workspace API are original. The
 * serial ordering is intentional: it is the deterministic diagnostic path
 * used by native UMAP whenever random_state is not None.
 */

namespace senko::umap_layout {
namespace {

constexpr size_t kAlignment = 16;
constexpr uint64_t kUint32Mask = 0xffff'ffffULL;

bool CheckedAdd(size_t left, size_t right, size_t* result) {
  if (right > std::numeric_limits<size_t>::max() - left) return false;
  *result = left + right;
  return true;
}

bool CheckedMultiply(size_t left, size_t right, size_t* result) {
  if (left != 0 && right > std::numeric_limits<size_t>::max() / left) {
    return false;
  }
  *result = left * right;
  return true;
}

bool AlignSize(size_t value, size_t* result) {
  constexpr size_t mask = kAlignment - 1;
  if (value > std::numeric_limits<size_t>::max() - mask) return false;
  *result = (value + mask) & ~mask;
  return true;
}

bool AddArrayBytes(size_t* total, size_t count, size_t item_bytes) {
  size_t aligned = 0;
  size_t bytes = 0;
  if (!AlignSize(*total, &aligned) ||
      !CheckedMultiply(count, item_bytes, &bytes) ||
      !CheckedAdd(aligned, bytes, total)) {
    return false;
  }
  return true;
}

class Workspace {
 public:
  Workspace(void* data, size_t size)
      : data_(static_cast<uint8_t*>(data)), size_(size) {}

  template <typename T>
  T* Allocate(size_t count) {
    size_t aligned = 0;
    size_t bytes = 0;
    size_t end = 0;
    if (!AlignSize(cursor_, &aligned) ||
        !CheckedMultiply(count, sizeof(T), &bytes) ||
        !CheckedAdd(aligned, bytes, &end) || end > size_) {
      return nullptr;
    }
    cursor_ = end;
    return reinterpret_cast<T*>(data_ + aligned);
  }

 private:
  uint8_t* data_;
  size_t size_;
  size_t cursor_ = 0;
};

bool IsWorkspaceAligned(const void* workspace) {
  return (reinterpret_cast<uintptr_t>(workspace) & (kAlignment - 1)) == 0;
}

bool ValidShape(int vertex_count, int dimension, int edge_count) {
  if (vertex_count <= 0 || dimension <= 0 || edge_count < 0) return false;
  size_t ignored = 0;
  return CheckedMultiply(static_cast<size_t>(vertex_count),
                         static_cast<size_t>(dimension), &ignored) &&
         CheckedMultiply(static_cast<size_t>(edge_count), sizeof(double),
                         &ignored) &&
         CheckedMultiply(static_cast<size_t>(vertex_count), size_t{3},
                         &ignored);
}

/*
 * Match the vector reduction shape generated by LLVM for UMAP's float32
 * fast-math rdist loop on the native reference machine. Keeping sixteen
 * independent accumulators also exposes straightforward SIMD to WebAssembly.
 */
float ReducedSquaredDistance(const float* left, const float* right,
                             int dimension) {
  float accumulator0 = 0.0f;
  float accumulator1 = 0.0f;
  float accumulator2 = 0.0f;
  float accumulator3 = 0.0f;
  float accumulator4 = 0.0f;
  float accumulator5 = 0.0f;
  float accumulator6 = 0.0f;
  float accumulator7 = 0.0f;
  float accumulator8 = 0.0f;
  float accumulator9 = 0.0f;
  float accumulator10 = 0.0f;
  float accumulator11 = 0.0f;
  float accumulator12 = 0.0f;
  float accumulator13 = 0.0f;
  float accumulator14 = 0.0f;
  float accumulator15 = 0.0f;

  const int vector_end = dimension & ~15;
  int coordinate = 0;
  for (; coordinate < vector_end; coordinate += 16) {
    const float difference0 = left[coordinate] - right[coordinate];
    const float difference1 = left[coordinate + 1] - right[coordinate + 1];
    const float difference2 = left[coordinate + 2] - right[coordinate + 2];
    const float difference3 = left[coordinate + 3] - right[coordinate + 3];
    const float difference4 = left[coordinate + 4] - right[coordinate + 4];
    const float difference5 = left[coordinate + 5] - right[coordinate + 5];
    const float difference6 = left[coordinate + 6] - right[coordinate + 6];
    const float difference7 = left[coordinate + 7] - right[coordinate + 7];
    const float difference8 = left[coordinate + 8] - right[coordinate + 8];
    const float difference9 = left[coordinate + 9] - right[coordinate + 9];
    const float difference10 = left[coordinate + 10] - right[coordinate + 10];
    const float difference11 = left[coordinate + 11] - right[coordinate + 11];
    const float difference12 = left[coordinate + 12] - right[coordinate + 12];
    const float difference13 = left[coordinate + 13] - right[coordinate + 13];
    const float difference14 = left[coordinate + 14] - right[coordinate + 14];
    const float difference15 = left[coordinate + 15] - right[coordinate + 15];
    accumulator0 += difference0 * difference0;
    accumulator1 += difference1 * difference1;
    accumulator2 += difference2 * difference2;
    accumulator3 += difference3 * difference3;
    accumulator4 += difference4 * difference4;
    accumulator5 += difference5 * difference5;
    accumulator6 += difference6 * difference6;
    accumulator7 += difference7 * difference7;
    accumulator8 += difference8 * difference8;
    accumulator9 += difference9 * difference9;
    accumulator10 += difference10 * difference10;
    accumulator11 += difference11 * difference11;
    accumulator12 += difference12 * difference12;
    accumulator13 += difference13 * difference13;
    accumulator14 += difference14 * difference14;
    accumulator15 += difference15 * difference15;
  }

  const float lane0 =
      (accumulator12 + accumulator8) + (accumulator4 + accumulator0);
  const float lane1 =
      (accumulator13 + accumulator9) + (accumulator5 + accumulator1);
  const float lane2 =
      (accumulator14 + accumulator10) + (accumulator6 + accumulator2);
  const float lane3 =
      (accumulator15 + accumulator11) + (accumulator7 + accumulator3);
  float result = (lane0 + lane1) + (lane2 + lane3);

  const int lane_end = dimension & ~3;
  float tail0 = result;
  float tail1 = 0.0f;
  float tail2 = 0.0f;
  float tail3 = 0.0f;
  for (; coordinate < lane_end; coordinate += 4) {
    const float difference0 = left[coordinate] - right[coordinate];
    const float difference1 = left[coordinate + 1] - right[coordinate + 1];
    const float difference2 = left[coordinate + 2] - right[coordinate + 2];
    const float difference3 = left[coordinate + 3] - right[coordinate + 3];
    tail0 += difference0 * difference0;
    tail1 += difference1 * difference1;
    tail2 += difference2 * difference2;
    tail3 += difference3 * difference3;
  }
  result = (tail0 + tail1) + (tail2 + tail3);

  for (; coordinate < dimension; ++coordinate) {
    const float difference = left[coordinate] - right[coordinate];
    result += difference * difference;
  }
  return result;
}

double Clip(double value) {
  if (value > 4.0) return 4.0;
  if (value < -4.0) return -4.0;
  return value;
}

struct TauState {
  int64_t values[3];
};

static_assert(sizeof(TauState) == sizeof(int64_t) * 3);

int64_t ArithmeticShiftRight(uint64_t bits, int shift) {
  if ((bits & (uint64_t{1} << 63)) == 0) {
    return static_cast<int64_t>(bits >> shift);
  }
  const uint64_t fill = ~uint64_t{0} << (64 - shift);
  return std::bit_cast<int64_t>((bits >> shift) | fill);
}

int32_t TauRandInt(TauState* state) {
  const uint64_t original0 = static_cast<uint64_t>(state->values[0]);
  const uint64_t original1 = static_cast<uint64_t>(state->values[1]);
  const uint64_t original2 = static_cast<uint64_t>(state->values[2]);

  const uint64_t left0 = ((original0 & 4294967294ULL) << 12) & kUint32Mask;
  const uint64_t mixed0 = ((original0 << 13) & kUint32Mask) ^ original0;
  state->values[0] = std::bit_cast<int64_t>(
      left0 ^ static_cast<uint64_t>(ArithmeticShiftRight(mixed0, 19)));

  const uint64_t left1 = ((original1 & 4294967288ULL) << 4) & kUint32Mask;
  const uint64_t mixed1 = ((original1 << 2) & kUint32Mask) ^ original1;
  state->values[1] = std::bit_cast<int64_t>(
      left1 ^ static_cast<uint64_t>(ArithmeticShiftRight(mixed1, 25)));

  const uint64_t left2 = ((original2 & 4294967280ULL) << 17) & kUint32Mask;
  const uint64_t mixed2 = ((original2 << 3) & kUint32Mask) ^ original2;
  state->values[2] = std::bit_cast<int64_t>(
      left2 ^ static_cast<uint64_t>(ArithmeticShiftRight(mixed2, 11)));

  const uint32_t result_bits = static_cast<uint32_t>(
      static_cast<uint64_t>(state->values[0]) ^
      static_cast<uint64_t>(state->values[1]) ^
      static_cast<uint64_t>(state->values[2]));
  return std::bit_cast<int32_t>(result_bits);
}

int PositiveModulo(int32_t value, int divisor) {
  int result = value % divisor;
  if (result < 0) result += divisor;
  return result;
}

int64_t WrappedAdd(int64_t left, int64_t right) {
  return std::bit_cast<int64_t>(static_cast<uint64_t>(left) +
                                static_cast<uint64_t>(right));
}

double PositiveGradientCoefficient(float distance_squared, double a,
                                   double b) {
  if (!(distance_squared > 0.0f)) return 0.0;
  const double distance = static_cast<double>(distance_squared);
  double result =
      -2.0 * a * b * std::pow(distance, b - 1.0);
  result /= a * std::pow(distance, b) + 1.0;
  return result;
}

double NegativeGradientCoefficient(float distance_squared, double a, double b,
                                   double gamma) {
  if (!(distance_squared > 0.0f)) return 0.0;
  const double distance = static_cast<double>(distance_squared);
  double result = 2.0 * gamma * b;
  result /= (0.001 + distance) * (a * std::pow(distance, b) + 1.0);
  return result;
}

}  // namespace

size_t SerialWorkspaceBytes(int vertex_count, int edge_count) {
  if (vertex_count <= 0 || edge_count < 0) return 0;
  size_t total = 0;
  if (!AddArrayBytes(&total, static_cast<size_t>(edge_count), sizeof(double)) ||
      !AddArrayBytes(&total, static_cast<size_t>(edge_count), sizeof(double)) ||
      !AddArrayBytes(&total, static_cast<size_t>(edge_count), sizeof(double)) ||
      !AddArrayBytes(&total, static_cast<size_t>(vertex_count) * size_t{3},
                     sizeof(int64_t))) {
    return 0;
  }
  return total;
}

int OptimizeSerial(float* embedding, int vertex_count, int dimension,
                   const int32_t* head, const int32_t* tail,
                   const double* epochs_per_sample, int edge_count,
                   const int64_t rng_state[3], int epoch_count, double a,
                   double b, double gamma, double negative_sample_rate,
                   void* workspace, size_t workspace_bytes) {
  if (!ValidShape(vertex_count, dimension, edge_count) || embedding == nullptr ||
      rng_state == nullptr || epoch_count < 0 || !std::isfinite(a) ||
      !std::isfinite(b) || !std::isfinite(gamma) ||
      !std::isfinite(negative_sample_rate) || a <= 0.0 || b <= 0.0 ||
      gamma < 0.0 || negative_sample_rate <= 0.0 ||
      (edge_count > 0 &&
       (head == nullptr || tail == nullptr || epochs_per_sample == nullptr))) {
    return kInvalidArgument;
  }

  const size_t required = SerialWorkspaceBytes(vertex_count, edge_count);
  if (required == 0) return kSizeOverflow;
  if (workspace == nullptr || !IsWorkspaceAligned(workspace) ||
      workspace_bytes < required) {
    return kInsufficientWorkspace;
  }

  Workspace arena(workspace, workspace_bytes);
  double* epochs_per_negative_sample =
      arena.Allocate<double>(static_cast<size_t>(edge_count));
  double* epoch_of_next_negative_sample =
      arena.Allocate<double>(static_cast<size_t>(edge_count));
  double* epoch_of_next_sample =
      arena.Allocate<double>(static_cast<size_t>(edge_count));
  TauState* rng_state_per_sample =
      arena.Allocate<TauState>(static_cast<size_t>(vertex_count));
  if (epochs_per_negative_sample == nullptr ||
      epoch_of_next_negative_sample == nullptr ||
      epoch_of_next_sample == nullptr || rng_state_per_sample == nullptr) {
    return kInsufficientWorkspace;
  }

  for (int edge = 0; edge < edge_count; ++edge) {
    if (head[edge] < 0 || head[edge] >= vertex_count || tail[edge] < 0 ||
        tail[edge] >= vertex_count ||
        !std::isfinite(epochs_per_sample[edge]) ||
        epochs_per_sample[edge] <= 0.0) {
      return kInvalidArgument;
    }
    const double negative_epoch =
        epochs_per_sample[edge] / negative_sample_rate;
    epochs_per_negative_sample[edge] = negative_epoch;
    epoch_of_next_negative_sample[edge] = negative_epoch;
    epoch_of_next_sample[edge] = epochs_per_sample[edge];
  }

  for (int vertex = 0; vertex < vertex_count; ++vertex) {
    const float* row =
        embedding + static_cast<size_t>(vertex) * dimension;
    for (int coordinate = 0; coordinate < dimension; ++coordinate) {
      if (!std::isfinite(row[coordinate])) return kInvalidArgument;
    }
    const float first_coordinate = row[0];
    const int64_t coordinate_bits =
        std::bit_cast<int64_t>(static_cast<double>(first_coordinate));
    for (int state_index = 0; state_index < 3; ++state_index) {
      rng_state_per_sample[vertex].values[state_index] =
          WrappedAdd(rng_state[state_index], coordinate_bits);
    }
  }

  double alpha = 1.0;
  for (int epoch = 0; epoch < epoch_count; ++epoch) {
    for (int edge = 0; edge < edge_count; ++edge) {
      if (epoch_of_next_sample[edge] > static_cast<double>(epoch)) continue;

      const int head_index = head[edge];
      const int tail_index = tail[edge];
      float* current =
          embedding + static_cast<size_t>(head_index) * dimension;
      float* other = embedding + static_cast<size_t>(tail_index) * dimension;

      float distance_squared =
          ReducedSquaredDistance(current, other, dimension);
      const double positive_coefficient =
          PositiveGradientCoefficient(distance_squared, a, b);
      for (int coordinate = 0; coordinate < dimension; ++coordinate) {
        const float difference = current[coordinate] - other[coordinate];
        const double gradient =
            Clip(positive_coefficient * static_cast<double>(difference));
        current[coordinate] = static_cast<float>(
            static_cast<double>(current[coordinate]) + gradient * alpha);
        other[coordinate] = static_cast<float>(
            static_cast<double>(other[coordinate]) - gradient * alpha);
      }
      epoch_of_next_sample[edge] += epochs_per_sample[edge];

      const double negative_epoch = epochs_per_negative_sample[edge];
      const int64_t negative_sample_count = static_cast<int64_t>(
          (static_cast<double>(epoch) -
           epoch_of_next_negative_sample[edge]) /
          negative_epoch);
      for (int64_t sample = 0; sample < negative_sample_count; ++sample) {
        const int negative_tail =
            PositiveModulo(TauRandInt(&rng_state_per_sample[head_index]),
                           vertex_count);
        other = embedding + static_cast<size_t>(negative_tail) * dimension;
        distance_squared =
            ReducedSquaredDistance(current, other, dimension);

        if (!(distance_squared > 0.0f) && head_index == negative_tail) {
          continue;
        }
        const double negative_coefficient =
            NegativeGradientCoefficient(distance_squared, a, b, gamma);
        for (int coordinate = 0; coordinate < dimension; ++coordinate) {
          double gradient = 0.0;
          if (negative_coefficient > 0.0) {
            const float difference = current[coordinate] - other[coordinate];
            gradient = Clip(negative_coefficient *
                            static_cast<double>(difference));
          }
          current[coordinate] = static_cast<float>(
              static_cast<double>(current[coordinate]) + gradient * alpha);
        }
      }
      epoch_of_next_negative_sample[edge] +=
          static_cast<double>(negative_sample_count) * negative_epoch;
    }

    /*
     * This intentionally mirrors UMAP 0.5.12's end-of-epoch update. Epochs
     * zero and one therefore both execute with alpha == initial_alpha.
     */
    alpha = 1.0 - (static_cast<double>(epoch) /
                   static_cast<double>(epoch_count));
  }
  return kSuccess;
}

}  // namespace senko::umap_layout
